name: CI (Build)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - run: cargo build --release --target=x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: -C target-feature=+crt-static

      - run: strip target/x86_64-unknown-linux-gnu/release/united-flarmnet

      - run: mkdir dist && cp target/x86_64-unknown-linux-gnu/release/united-flarmnet dist
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
